-- BestDel Supabase archive/chat schema.
-- Run this once in the Supabase SQL Editor for the project configured by
-- SUPABASE_URL and SUPABASE_ANON_KEY.

create table if not exists public.archives (
  id bigint generated by default as identity primary key,
  owner_user_id text,
  name text not null check (length(trim(name)) between 1 and 120),
  topic text not null check (length(trim(topic)) between 3 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  owner_user_id text,
  archive_id bigint not null references public.archives(id) on delete restrict,
  title text not null check (length(trim(title)) between 1 and 200),
  created_at timestamptz not null default now()
);

alter table public.archives
  add column if not exists owner_user_id text;

alter table public.conversations
  add column if not exists owner_user_id text;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  metadata_json text,
  run_id text,
  run_status text,
  run_phase text,
  run_last_heartbeat_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.archive_contexts (
  archive_id bigint primary key references public.archives(id) on delete cascade,
  summary text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.archive_research_angles (
  archive_id bigint primary key references public.archives(id) on delete cascade,
  angles_json text not null default '[]',
  meta_json text not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.archive_intelligence_profiles (
  id bigint generated by default as identity primary key,
  archive_id bigint not null unique references public.archives(id) on delete cascade,
  agenda_text text,
  committee_type text,
  agenda_class text,
  primary_dimensions text,
  completed_divisions text,
  evidence_registry text,
  debate_utility_log text,
  dimension_engine_hash text,
  session_count integer,
  updated_at timestamptz not null default now()
);

create index if not exists conversations_archive_id_created_at_idx
  on public.conversations (archive_id, created_at);

create index if not exists archives_owner_user_id_created_at_idx
  on public.archives (owner_user_id, created_at);

create index if not exists conversations_owner_archive_created_at_idx
  on public.conversations (owner_user_id, archive_id, created_at);

create index if not exists messages_conversation_id_created_at_idx
  on public.messages (conversation_id, created_at);

alter table public.archives enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.archive_contexts enable row level security;
alter table public.archive_research_angles enable row level security;
alter table public.archive_intelligence_profiles enable row level security;

grant select, insert, update, delete on table
  public.archives,
  public.conversations,
  public.messages,
  public.archive_contexts,
  public.archive_research_angles,
  public.archive_intelligence_profiles
to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "BestDel backend anon full access archives" on public.archives;
drop policy if exists "BestDel user archives" on public.archives;
create policy "BestDel user archives"
  on public.archives for all to anon, authenticated
  using (owner_user_id = auth.uid()::text)
  with check (owner_user_id = auth.uid()::text);

drop policy if exists "BestDel backend anon full access conversations" on public.conversations;
drop policy if exists "BestDel user conversations" on public.conversations;
create policy "BestDel user conversations"
  on public.conversations for all to anon, authenticated
  using (owner_user_id = auth.uid()::text)
  with check (
    owner_user_id = auth.uid()::text
    and exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  );

drop policy if exists "BestDel backend anon full access messages" on public.messages;
drop policy if exists "BestDel user messages" on public.messages;
create policy "BestDel user messages"
  on public.messages for all to anon, authenticated
  using (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.owner_user_id = auth.uid()::text
    )
  )
  with check (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.owner_user_id = auth.uid()::text
    )
  );

drop policy if exists "BestDel backend anon full access archive contexts" on public.archive_contexts;
drop policy if exists "BestDel user archive contexts" on public.archive_contexts;
create policy "BestDel user archive contexts"
  on public.archive_contexts for all to anon, authenticated
  using (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  )
  with check (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  );

drop policy if exists "BestDel backend anon full access archive research angles" on public.archive_research_angles;
drop policy if exists "BestDel user archive research angles" on public.archive_research_angles;
create policy "BestDel user archive research angles"
  on public.archive_research_angles for all to anon, authenticated
  using (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  )
  with check (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  );

drop policy if exists "BestDel backend anon full access archive intelligence profiles" on public.archive_intelligence_profiles;
drop policy if exists "BestDel user archive intelligence profiles" on public.archive_intelligence_profiles;
create policy "BestDel user archive intelligence profiles"
  on public.archive_intelligence_profiles for all to anon, authenticated
  using (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  )
  with check (
    exists (
      select 1 from public.archives a
      where a.id = archive_id and a.owner_user_id = auth.uid()::text
    )
  );
